spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Flrnl3570@
    url: jdbc:mysql://localhost:3306/jeju
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: grand2181@gmail.com
    password: nxhbdmtjrkawngex
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

csv:
  file:
    path: classpath:static/food.csv
